---
output: 
  bookdown::html_document2: 
#  bookdown::pdf_document2:
    keep_tex: yes
    keep_md: yes
    toc: false
    number_sections: false
#bibliography: NECCC-test.bib
---


```{r , include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      fig.dim = c(10, 6), 
                      fig.fullwidth=TRUE, 
                      dev = "jpeg",
                      dpi = 900)
library(readr) # for read_csv
library(emmeans) # for join_test
library(ggResidpanel)
library(tidyverse)
library(kableExtra)
library(ggplot2); theme_set(theme_bw())
library(flextable)
library(patchwork)
library(magrittr)
library(nls2)
library(nlstools)
library(multcompView) # for compact letter display
```


Arithmetic means of speculative coverage are in Figure \@ref(fig:summ-coverage).  
```{r summ-coverage, echo = FALSE, fig.cap = "Arithmetic means of crop speculative coverage."}
coverage <- read_csv("../2-Data/Clean/coverage_clean.csv")

coverage$species <- factor(coverage$species, levels = c("Control",
                                                            "Arugula" ,    
                                                            "Broadleaf mustard",
                                                            "Brown mustard",
                                                            "Collard",
                                                            "Kale",
                                                            "Mustard",
                                                            "Oriental mustard",
                                                            "Radish",
                                                            "Rapeseed",
                                                            "Red clover",
                                                            "Turnip" ))

coverage$species2 <- factor(coverage$species, levels = c("Control",
                                                            "Arugula (Eruca vesicaria)" ,    
                                                            "Broadleaf mustard (Brassica juncea)",
                                                            "Brown mustard (Brassica juncea)",
                                                            "Collard (Brassica oleracea)",
                                                            "Kale (Brassica oleracea)",
                                                            "Mustard (Sinapis alba)",
                                                            "Oriental mustard (Brassica juncea)",
                                                            "Radish (Raphanus raphanistrum subsp. sativus)",
                                                            "Rapeseed (Brassica napus)",
                                                            "Red clover (Trifolium pratense)",
                                                            "Turnip (Brassica rapa)" ))


# Make sure that the levels are kept  

#levels(factor(coverage$treatment))   #A B C D E F G H I J K L N

coverage %>%
  filter(treatment != "N") %>%
  dplyr::group_by(treatment, species) %>%
    mutate(sp.coverage = mean(speculative.pct.coverage),
    sd = sd(speculative.pct.coverage),
    n = n(),
    se = sd / sqrt(n)) %>%
  ggplot(aes(x = species, y = sp.coverage)) +
  geom_bar(stat = "identity", position = "dodge", fill = "#B31B1B") + 
  geom_errorbar( aes(x = species, ymin = sp.coverage - sd, ymax = sp.coverage + sd), width=0.4, colour="black", alpha=0.9, size=1) + 
  ylab("Speculative coverage (%)" ) +
  xlab(" ") + 
   theme(legend.title= element_blank()) + 
  scale_x_discrete(guide = guide_axis(angle = 40)) 
```


```{r}
coverage.lm1 <- lm(speculative.pct.coverage   ~ as.factor(block) + species , data = coverage, subset = (treatment != "N"))
resid_panel(coverage.lm1)

joint_tests(coverage.lm1)
```

```{r cover-emmip, fig.cap = "Estimate speculative percent coverage of different cover crop species"}
plot(emmeans(coverage.lm1 , "species"), comparisons = TRUE) + 
#    scale_y_discrete(limits = rev(levels(species))) +
  xlab("Speculative coverage (%)" ) +
  ylab("Cover crop")  + 
#  coord_flip() +
  theme(text = element_text(size=20)) +
  theme_classic()
```
```{r}
coverage.emm <- emmeans(coverage.lm1 , "species") %>% as.data.frame()

anova <- aov(speculative.pct.coverage   ~ as.factor(block) + species , data = coverage, subset = (treatment != "N"))

# Tukey's test
tukey <- TukeyHSD(anova )

# compact letter display
cld <- multcompLetters4(anova, tukey)
# https://www.mathiasecology.com/code 
cld.df <- data.frame(multcompLetters(TukeyHSD(anova)$species[,4])$Letters) 

cld.df$species <- rownames(cld.df)

coverage.emm %>% left_join(cld.df, by = "species")
```

```{r coverage-letters}
coverage %>%
  filter(treatment != "N") %>%
  dplyr::group_by(treatment, species2) %>%
    mutate(sp.coverage = mean(speculative.pct.coverage),
    sd = sd(speculative.pct.coverage),
    n = n(),
    se = sd / sqrt(n)) %>%
  left_join(cld.df, by = "species") %>%
  ggplot(aes(x = species, y = sp.coverage)) +
  geom_bar(stat = "identity", position = "dodge", fill = "#B31B1B") + 
  geom_errorbar( aes(x = species, ymin = sp.coverage - sd, ymax = sp.coverage + sd), width=0.4, colour="black", alpha=0.9, size=1) + 
  geom_text(aes(y = 59, x = species, label = multcompLetters.TukeyHSD.anova..species...4...Letters)) +
  ylab("Speculative coverage (%)" ) +
  xlab(" ") + 
   theme(legend.title= element_blank()) + 
  scale_x_discrete(labels= expression("Arugula \n (Eruca vesicaria)" ,
                            "Broadleaf mustard \n (Brassica juncea)",
                            "Brown mustard \n (Brassica juncea)",
                            "Collard \n (Brassica oleracea)",
                            "Kale \n (Brassica oleracea)",
                            "Mustard \n (Sinapis alba)",
                            "Oriental mustard \n (Brassica juncea)",
                            "Radish \n (Raphanus raphanistrum subsp. sativus)",
                            "Rapeseed \n (Brassica napus)",
                            "Red clover \n (Trifolium pratense)",
                            "Turnip \n (Brassica rapa)" ),
                   guide = guide_axis(angle = 40)) # + scale_x_discrete(guide = guide_axis(angle = 40)) 
```